Task 5
Aydar710/androidHomework pull request #6
Opened 2018-10-15 20:17 UTC by Aydar710

![photo5343987104016869790](https://user-images.githubusercontent.com/32329290/46975796-44bfde00-d0d0-11e8-9430-87bea8eb14bc.jpg)

2018-10-15 22:38 UTC, NailShaykhrazievItis requested changes

2018-10-15 22:38 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/aydar/editingusersprofile/NavigationActivity.kt
> +                fragmentTransaction.replace(R.id.frame_content, fragment)
общий блок кода мог в метод вынести

2018-10-15 22:38 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/aydar/editingusersprofile/TabsFragmentAdapter.kt
> +                0 -> {
ууу хардкод все равно оставил, я ж говорил создавать из вне лист.

2018-10-15 22:38 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/aydar/editingusersprofile/fragments/RecyclerFragment.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
методы по жц отсортировываются

2018-10-15 22:38 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/aydar/editingusersprofile/miracle/AdapterMiracle.kt
> +
имхо тут пустые строки не нужны. Ты не разделяешь визаульно какую то логику. Везде идет биндинг данных

2018-10-15 22:38 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/aydar/editingusersprofile/miracle/AdapterMiracle.kt
> +                return o1!!.name.compareTo(o2!!.name)
Я промолчу!!

2018-10-15 22:38 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/aydar/editingusersprofile/miracle/MiracleDetailActivity.kt
> +        txtLocation = txt_miracle_location
Зачем? пиши сразу txt_miracle_order.text = miracle.order.toString()

2018-10-15 22:38 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/fragment_recycler.xml
> +        android:id="@+id/recycler_fr"
скорее rv_miracles

2018-10-15 22:38 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/fragment_recycler.xml
> +        tools:context=".MainActivity" />
контекст здесь не нужен. Лучше tools:listitem="@layout/card_miracle

2018-10-15 22:38 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/fragment_view_pager.xml
> +    <android.support.v7.widget.Toolbar
Объедини тулбар и таблайоут в аппбарлайоут

2018-10-16 17:02 UTC, Aydar710 commented on app/src/main/java/com/example/aydar/editingusersprofile/TabsFragmentAdapter.kt
> +                0 -> {
Забыл глянуть ToDoList :D

2018-10-16 18:59 UTC, NailShaykhrazievItis approved these changes

2018-10-17 17:02 UTC, closed without merging